# LOCALHOST

### Get all books
GET http://localhost:4000/books
### Get One book 1
 GET http://localhost:4000/books/634382a36e51ba875443511a
### Get book 2
GET http://localhost:4000/books/634382a36e51ba875443511a
### Get book 3
GET http://localhost:4000/books/634382a36e51ba875443511b
### Create book 
POST http://localhost:4000/books HTTP/1.1
content-type: application/json

{
    "bookTitle": "The Great Gasby",
    "authorName": "F. Scott Fitzgerald",
    "bookPrice": "6.67",
    "bookEdition": "3rd edition",
    "publishYear": "1925",
    "pageNumber": "180",
    "BookGenre": ["Historical Fiction", "American", "Romance"]
}
### PUT book 
PUT http://localhost:4000/books/6349b357fbed97704fd6d78f HTTP/1.1
content-type: application/json

{
    "bookTitle": "To Kill a Mockingbird",
    "authorName": "Harper Lee",
    "bookPrice": "8.67",
    "bookEdition": "2nd edition",
    "publishYear": "1960",
    "pageNumber": "323",
    "BookGenre": ["Historical Fiction", "American", "Young Adult"]
}
### DELETE book 
DELETE http://localhost:4000/books/6349b629897204162e5f1630 HTTP/1.1


### Render

GET https://bookstore-hliu.onrender.com/books
### Get book 1
GET https://bookstore-hliu.onrender.com/books/634382a36e51ba8754435119
### Get book 2
GET https://bookstore-hliu.onrender.com/books/634382a36e51ba875443511a
### Get book 3
GET https://bookstore-hliu.onrender.com/books/634382a36e51ba875443511b
### Post book
POST https://bookstore-hliu.onrender.com/books HTTP/1.1
content-type: application/json

{
    "bookTitle": "The Great Gasby",
    "authorName": "F. Scott Fitzgerald",
    "bookPrice": "6.67",
    "bookEdition": "1st edition",
    "publishYear": "1925",
    "pageNumber": "180",
    "BookGenre": ["Historical Fiction", "American", "Romance"]
}
### Update book
PUT https://bookstore-hliu.onrender.com/books/63439cde628c3acd97cdb3d9 HTTP/1.1
content-type: application/json

{
    "bookTitle": "The Great Gasby",
    "authorName": "F. Scott Fitzgerald",
    "bookPrice": "6.67",
    "bookEdition": "2nd edition",
    "publishYear": "1925",
    "pageNumber": "180",
    "BookGenre": ["Historical Fiction", "American", "Romance"]
}

### DELETE book 
DELETE https://bookstore-hliu.onrender.com/books/63439cde628c3acd97cdb3d9 HTTP/1.1


### POST book
POST http://localhost:4000/books HTTP/1.1
content-type: application/json

{
    "bookTitle": "The Great Gasby tester",
    "authorName": "F. Scott Fitzgerald",
    "bookPrice": "6.67",
    "bookEdition": "3rd edition",
    "publishYear": "1925",
    "pageNumber": "180",
    "BookGenre": ["Historical Fiction", "American", "Romance"]
}

### PUT book 
PUT http://localhost:4000/books/634b89f1a555c56a92467764 HTTP/1.1
content-type: application/json

{
    "bookTitle": "To Kill a Mockingbird",
    "authorName": "Harper Lee",
    "bookPrice": "8.67",
    "bookEdition": "2nd edition",
    "publishYear": "1960",
    "pageNumber": "323",
    "BookGenre": ["Historical Fiction", "American", "Young Adult"]
}


# User creation and testing

### Create a new User
POST http://localhost:4000/register HTTP/1.1
content-type: application/json

{
    "firstName": "Keanu",
    "lastName": "Reeves",
    "email": "bikelord@hotmail.com",
    "password":"mygirlfriend"
}
